spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://mydesk.cmibjlimzo3y.ap-northeast-2.rds.amazonaws.com:3306/mydesk
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 90117567144-irk6kfcr3vusgis72vjkjbbvc2dl7ato.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email

          naver:
            client-id: 8TmJ2DyZgC_SN0Wsm6g6
            client-secret: DEEAoQWwSo
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver

          kakao:
            client-id: 6b307c5eb47d8ff944f62ef6ce9a2d97
            client-secret: SQ91dAJ0tK11epj6yLiD0BXaGRKw4rbh
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: POST
            scope: profile_nickname, account_email, profile_image


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

cloud:
  aws:
    credentials:
      accessKey: AKIATC26VJ6QYL5PXXM2
      secretKey: 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
    s3:
      bucket: mydesk-img
    region:
      static: ap-northeast-2
    stack:
      auto: false

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        storage_engine: innodb
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: admin
      maximum-pool-size: 20
  session:
    store-type: jdbc
  h2:
    console:
      enabled: true

  security:
    exclude: /**

---

spring:
  config:
    activate:
      on-profile: real

logging:
  config: classpath:log4j2-real.xml
